/* @file Кодек АТОЛ-а. */

#pragma once

#include "Hardware/Common/CodecBase.h"

//---------------------------------------------------------------------------
class AtolTextCodec : public CodecBase {
public:
    AtolTextCodec() {
        m_Name = CHardware::Codepages::ATOL;
        m_MIB = 3002;
        m_MinValueActive = 0;

        m_Data.add('\x00', "А");
        m_Data.add('\x10', "Р");
        m_Data.add('\x20', " ");
        m_Data.add('\x30', "0");
        m_Data.add('\x01', "Б");
        m_Data.add('\x11', "С");
        m_Data.add('\x21', "!");
        m_Data.add('\x31', "1");
        m_Data.add('\x02', "В");
        m_Data.add('\x12', "Т");
        m_Data.add('\x22', "\"");
        m_Data.add('\x32', "2");
        m_Data.add('\x03', "Г");
        m_Data.add('\x13', "У");
        m_Data.add('\x23', "#");
        m_Data.add('\x33', "3");
        m_Data.add('\x04', "Д");
        m_Data.add('\x14', "Ф");
        m_Data.add('\x24', "№");
        m_Data.add('\x34', "4");
        m_Data.add('\x05', "Е");
        m_Data.add('\x15', "Х");
        m_Data.add('\x25', "%");
        m_Data.add('\x35', "5");
        m_Data.add('\x06', "Ж");
        m_Data.add('\x16', "Ц");
        m_Data.add('\x26', "&");
        m_Data.add('\x36', "6");
        m_Data.add('\x07', "З");
        m_Data.add('\x17', "Ч");
        m_Data.add('\x27', "’");
        m_Data.add('\x37', "7");
        m_Data.add('\x08', "И");
        m_Data.add('\x18', "Ш");
        m_Data.add('\x28', "(");
        m_Data.add('\x38', "8");
        m_Data.add('\x09', "Й");
        m_Data.add('\x19', "Щ");
        m_Data.add('\x29', ")");
        m_Data.add('\x39', "9");
        m_Data.add('\x0A', "К");
        m_Data.add('\x1A', "Ъ");
        m_Data.add('\x2A', "*");
        m_Data.add('\x3A', ":");
        m_Data.add('\x0B', "Л");
        m_Data.add('\x1B', "Ы");
        m_Data.add('\x2B', "+");
        m_Data.add('\x3B', ";");
        m_Data.add('\x0C', "М");
        m_Data.add('\x1C', "Ь");
        m_Data.add('\x2C', ",");
        m_Data.add('\x3C', "<");
        m_Data.add('\x0D', "Н");
        m_Data.add('\x1D', "Э");
        m_Data.add('\x2D', "-");
        m_Data.add('\x3D', "=");
        m_Data.add('\x0E', "О");
        m_Data.add('\x1E', "Ю");
        m_Data.add('\x2E', ".");
        m_Data.add('\x3E', ">");
        m_Data.add('\x0F', "П");
        m_Data.add('\x1F', "Я");
        m_Data.add('\x2F', "/");
        m_Data.add('\x3F', "?");

        m_Data.add('\x40', "@");
        m_Data.add('\x50', "P");
        m_Data.add('\x60', "`");
        m_Data.add('\x70', "p");
        m_Data.add('\x41', "A");
        m_Data.add('\x51', "Q");
        m_Data.add('\x61', "a");
        m_Data.add('\x71', "q");
        m_Data.add('\x42', "B");
        m_Data.add('\x52', "R");
        m_Data.add('\x62', "b");
        m_Data.add('\x72', "r");
        m_Data.add('\x43', "C");
        m_Data.add('\x53', "S");
        m_Data.add('\x63', "c");
        m_Data.add('\x73', "s");
        m_Data.add('\x44', "D");
        m_Data.add('\x54', "T");
        m_Data.add('\x64', "d");
        m_Data.add('\x74', "t");
        m_Data.add('\x45', "E");
        m_Data.add('\x55', "U");
        m_Data.add('\x65', "e");
        m_Data.add('\x75', "u");
        m_Data.add('\x46', "F");
        m_Data.add('\x56', "V");
        m_Data.add('\x66', "f");
        m_Data.add('\x76', "v");
        m_Data.add('\x47', "G");
        m_Data.add('\x57', "W");
        m_Data.add('\x67', "g");
        m_Data.add('\x77', "w");
        m_Data.add('\x48', "H");
        m_Data.add('\x58', "X");
        m_Data.add('\x68', "h");
        m_Data.add('\x78', "x");
        m_Data.add('\x49', "I");
        m_Data.add('\x59', "Y");
        m_Data.add('\x69', "i");
        m_Data.add('\x79', "y");
        m_Data.add('\x4A', "J");
        m_Data.add('\x5A', "Z");
        m_Data.add('\x6A', "j");
        m_Data.add('\x7A', "z");
        m_Data.add('\x4B', "K");
        m_Data.add('\x5B', "[");
        m_Data.add('\x6B', "k");
        m_Data.add('\x7B', "{");
        m_Data.add('\x4C', "L");
        m_Data.add('\x5C', "\\");
        m_Data.add('\x6C', "l");
        m_Data.add('\x7C', "|");
        m_Data.add('\x4D', "M");
        m_Data.add('\x5D', "]");
        m_Data.add('\x6D', "m");
        m_Data.add('\x7D', "}");
        m_Data.add('\x4E', "N");
        m_Data.add('\x5E', "^");
        m_Data.add('\x6E', "n");
        m_Data.add('\x7E', "~");
        m_Data.add('\x4F', "O");
        m_Data.add('\x5F', "_");
        m_Data.add('\x6F', "o");
        m_Data.add('\x7F');

        m_Data.add('\x80', "а");
        m_Data.add('\x90', "р");
        m_Data.add('\xA0', "$");
        m_Data.add('\xF0', "Ё");
        m_Data.add('\x81', "б");
        m_Data.add('\x91', "с");
        m_Data.add('\xA1', "€");
        m_Data.add('\xF1', "ё");
        m_Data.add('\x82', "в");
        m_Data.add('\x92', "т");
        m_Data.add('\xA2', "—");
        m_Data.add('\x83', "г");
        m_Data.add('\x93', "у");
        m_Data.add('\x84', "д");
        m_Data.add('\x94', "ф");
        m_Data.add('\x85', "е");
        m_Data.add('\x95', "х");
        m_Data.add('\x86', "ж");
        m_Data.add('\x96', "ц");
        m_Data.add('\x87', "з");
        m_Data.add('\x97', "ч");
        m_Data.add('\x88', "и");
        m_Data.add('\x98', "ш");
        m_Data.add('\x89', "й");
        m_Data.add('\x99', "щ");
        m_Data.add('\x8A', "к");
        m_Data.add('\x9A', "ъ");
        m_Data.add('\x8B', "л");
        m_Data.add('\x9B', "ы");
        m_Data.add('\x8C', "м");
        m_Data.add('\x9C', "ь");
        m_Data.add('\x8D', "н");
        m_Data.add('\x9D', "э");
        m_Data.add('\x8E', "о");
        m_Data.add('\x9E', "ю");
        m_Data.add('\x8F', "п");
        m_Data.add('\x9F', "я");
    }
};

//---------------------------------------------------------------------------
